# Python learning notes

# Python Basics

## Interpreter mode
- enter interpreter mode by typing python on terminal
- exit interpreter mode by typing ctrl+d

## Naming conventions
- Class names start with an uppercase letter 
- Starting an identifier with a single leading underscore indicates that the identifier is private 
- Starting an identifier with two leading underscores indicates a strongly private identifier 
- If the identifier also ends with two trailing underscores, the identifier is a language-defined special name

## Python Keywords
    and        exec        not
    assert     finally     or
    break      for         pass
    class      from        print
    continue   global      raise
    def        if          return
    del        import      try
    elif       in          while
    else       is          with
    except     lambda      yield

## Python membership operators
- Python’s membership operators test for membership in a sequence, such as strings, lists, or tuples
- There are two membership operators 'in', 'not in'

### in
- 'in' evaluates to true if it finds a variable in the specified sequence and false otherwise

In [9]:
# example
ls = [1, 'test', 4, 9]
print ('test in ls:', 'test' in ls)
print ('4 in ls:', 4 in ls)

test in ls: True
4 in ls: True


### not in
- 'not in' evaluates to true if it does not finds a variable in the specified sequence and false otherwise

## Python identity operators
- Identity operators compare the memory locations of two objects. 
- There are two Identity operators 'is', 'is not'

### is
- 'is' evaluates to true if the variables on either side of the operator point to the same object and false otherwise

In [34]:
# example
x=2; y=2
print ('x is y:', x is y)

x is y: True


### is not
'is not' evaluates to false if the variables on either side of the operator point to the same object and true otherwise

In [ ]:
## built-in functions 

### dir ([object])
- Without arguments, return the list of names in the current local scope
- With an argument, attempt to return a list of valid attributes for that object

In [1]:
# example
print (dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [33]:
# example
print(dir(str))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


### enumerate (iterable, start=0)
- Return an enumerate object. iterable must be a sequence

In [2]:
# example
lst = [1, 'hi', 4]
for idx, ls in enumerate(lst):
 print (idx, ls)

0 1
1 hi
2 4


### help ([object])
- Invoke the built-in help system. If no argument is given, the interactive help system starts on the interpreter console
- If the argument is a string, then the string is looked up as the name of a module, function, class, method, keyword, or documentation topic, and a help page is printed on the console

In [3]:
# example
help(list.append)

Help on method_descriptor:

append(...)
    L.append(object) -> None -- append object to end



### id (object)
- Returns the “identity” of an object
- This is an integer which is guaranteed to be unique and constant for this object during its lifetime

In [15]:
# example
val1 = 5
val2 = 5.0
print(id(val1))
print(id(val2))

1490805584
71943104


### input ([prompt])
- If the prompt argument is present, it is written to standard output without a trailing newline
- The function then reads a line from input, converts it to a string (stripping a trailing newline), and returns that
- when EOF is read, EOFError is raised

### open
- Syntax: open(file, mode=’r’, buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)

### sorted
- Return a new sorted list from the items in iterable
- Syntax: sorted(iterable[, key][, reverse])

## use 'format' for print

In [16]:
#example
name = 'bond' 
age = 25

print ('{0} is {1} years old'.format(name, age))

# use format without index
print ('{} is {} years old: without index'.format(name, age))

# use format for a different format specifier
print ('{0:.3f}'.format(1.0/3))

bond is 25 years old
bond is 25 years old: without index
0.333


## Print without newline : end = ''
- By default python’s print() function ends with a newline.
- Python’s print() function comes with a parameter called ‘end’. By default, the value of this parameter is ‘\n’
- You can end a print statement with any character/string using this parameter

In [41]:
# example
# by default creates newlines
print ('welcome to')
print ('python in multiple lines')

# edit with end=''
print ('welcome to', end=' ++ ')
print ('python in single line')

welcome to
python in multiple lines
welcome to ++ python in single line


## data type conversion
- To convert between types, you simply use the type name as a function
- examples: int(x [,base]), tuple(s), dict(d)

# Strings
- Python allows for either pairs of single or double quotes
- Subsets of strings can be taken using the slice operator ([ ] and [:] )
- indexes starting at 0 in the beginning of the string and **working their way from -1 at the end**
- The plus (+) sign is the string concatenation operator and the asterisk (*) is the repetition operator

In [4]:
# example
str = 'Hello World!'

print ('str:', str)          # Prints complete string
print ('str[0]:', str[0])       # Prints first character of the string
print ('str[2:7]:', str[2:7])     # Prints characters starting from 3rd to 7th
print ('str[2:]:', str[2:])      # Prints string starting from 3rd character
print ('str * 2:', str * 2)          # Prints string two times
print ('str + TEST:', str + "TEST")  # Prints concatenated string

str: Hello World!
str[0]: H
str[2:7]: llo W
str[2:]: llo World!
str * 2: Hello World!Hello World!
str + TEST: Hello World!TEST


## + operation on strings

In [5]:
a = 'i'
b = 'am'
s = a + b
print ('+ operator on strings concatenates the result')
print ('i+am=', s)

+ operator on strings concatenates the result
i+am= iam


## 'format' to concat strings

In [6]:
str2 = 'strings'
str3 = 'can be added'
str4 = '{} {} using format'.format(str2, str3)
print (str4)

strings can be added using format


# Lists
- A list contains items separated by commas and enclosed within square brackets []
- To some extent, lists are similar to arrays in C
- One difference between them is that all the items belonging to a list can be of different data type

In [7]:
# example
list = [ 'abcd', 786 , 2.23, 'john', 70.2 ]
tinylist = [123, 'john']

print ('list:', list)          # Prints complete list
print ('list[0]:', list[0])       # Prints first element of the list
print ('list[1:3]:', list[1:3])     # Prints elements starting from 2nd till 3rd 
print ('list[2:]:', list[2:])      # Prints elements starting from 3rd element
print ('tinylist * 2:', tinylist * 2)  # Prints list two times
print ('list + tinylist:', list + tinylist) # Prints concatenated lists

list: ['abcd', 786, 2.23, 'john', 70.2]
list[0]: abcd
list[1:3]: [786, 2.23]
list[2:]: [2.23, 'john', 70.2]
tinylist * 2: [123, 'john', 123, 'john']
list + tinylist: ['abcd', 786, 2.23, 'john', 70.2, 123, 'john']


## Slicing of Lists, Strings
- slicing syntax is list[start:end:step]
- **start and end can be -ve indexes also and step also can be -ve **

In [21]:
# example
lst = [0, 1, 2, 3, 4, 5, 6]
#-ve index's
# lst = [-7, -6, -5, -4, -3, -2, -1]

lst1 = lst[2:5]
print ('list result with slicing and last index element is not included: ', lst1, '\n')

lst1 = lst[:]
print ('list result without any index is full list: ', lst1, '\n')

lst1 = lst[::2]
print ('list result with step of 2: ', lst1, '\n')

lst1 = lst[-6:-1]
print ('list result with -ve indexing: ', lst1, '\n')

lst1 = lst[6:1:-1]
print ('list result with -ve step: ', lst1, '\n')

list result with slicing and last index element is not included:  [2, 3, 4] 

list result without any index is full list:  [0, 1, 2, 3, 4, 5, 6] 

list result with step of 2:  [0, 2, 4, 6] 

list result with -ve indexing:  [1, 2, 3, 4, 5] 

list result with -ve step:  [6, 5, 4, 3, 2] 



## Delete list elements

In [22]:
list1 = ['physics', 'chemistry', 1997, 2000];

print ('list1:', list1)
del list1[2];
print ("After deleting value at index 2 : ")
print ('list1:', list1)

list1: ['physics', 'chemistry', 1997, 2000]
After deleting value at index 2 : 
list1: ['physics', 'chemistry', 2000]


## Built-in List functions and methods

### help: get help using method name

In [10]:
# help: get help using method name
print(help(list.append))

Help on built-in function append:

append(...) method of builtins.list instance
    L.append(object) -> None -- append object to end

None


### functions

In [11]:
print ('''- len(list), cmp(list), max(list), sum(list), sorted(list) ''')

- len(list), cmp(list), max(list), sum(list), sorted(list) 


### zip ()
- zip function combines multiple iterables to single iterable tuple pairs

In [37]:
# example
ls1 = ['one', 'two']
ls2 = ['1', '2']
ls3 = ['first', 'second']
ls4 = zip(ls1, ls2, ls3)

print ('tuples in zipped iterable')
for tp in ls4:
    print (tp)

tuples in zipped iterable
('one', '1', 'first')
('two', '2', 'second')


## methods

In [39]:
print('''- list.append(obj), list.extern(obj) ''')

- list.append(obj), list.extern(obj) 


### join method
- method join() returns a string in which the string elements of sequence have been joined by str separator
- **syntax: str.join(sequence)**

In [35]:
# example
ls = ['hi', 'how', 'are', 'you']
str1 = ' - '.join(ls)
print(str1)

hi - how - are - you


### split method
- method split() returns a list of all the words in the string, using str as the separator (splits on all whitespace if left unspecified)
- optionally limiting the number of splits to num
- **syntax: str.split(str="", num=string.count(str))**

In [28]:
# example
ls_new = str1.split(' - ')
print (ls_new)

['hi', 'how', 'are', 'you']


# tuples
- A tuple is another sequence data type that is similar to the list. tuples are enclosed within parentheses
- The main differences between lists and tuples are: 
    - tuples are immutable, i.e., they can't be updated
- Tuples can be thought of as read-only lists

# Dictionary
- Python's dictionaries are kind of hash table type
- A dictionary key can be almost any Python type, but are usually numbers or strings
- Values, on the other hand, can be any arbitrary Python object
- Dictionaries are enclosed by curly braces ({ }) and values can be assigned and accessed using square braces []

## dictionary examples

In [12]:
# example
dict = {}
dict['one'] = "This is one"
dict[2]     = "This is two"

tinydict = {'name': 'john','code':6734, 'dept': 'sales'}

print ('dict:', dict['one'])       # Prints value for 'one' key
print ('dict[2]:', dict[2])           # Prints value for 2 key
print ('tinydict:', tinydict)          # Prints complete dictionary
print ('tinydict.keys():', tinydict.keys())   # Prints all the keys
print ('tinydict.values():', tinydict.values()) # Prints all the values

dict: This is one
dict[2]: This is two
tinydict: {'name': 'john', 'code': 6734, 'dept': 'sales'}
tinydict.keys(): dict_keys(['name', 'code', 'dept'])
tinydict.values(): dict_values(['john', 6734, 'sales'])


## looping dictionary items

In [13]:
dict = {'name': 'john','code':6734, 'dept': 'sales'}
for key, value in dict.items():
  print ('key: ', key, 'value: ', value)

key:  name value:  john
key:  code value:  6734
key:  dept value:  sales


# Comprehensions
- comprehensions are concise way to create list/dictionaries
- syntax: lst = [expression for item in list if condition] 
- the variables name in expression and for loop should same

## List comprehensions

In [31]:
# genarate list of numbers
lst = [num for num in range(6)]
print ('list of numbers :', lst)

# genarate list of squrares with expression
lst = [num * num for num in range(6)]
print ('list of squares: ', lst)

# genarate list of even numbers with expression and condition
lst = [num for num in range(6) if num%2 == 0]
print ('list of even numbers: ', lst)

# two for loops in comprehension (to create tuple pairs)
str1 = 'ab'
lst = [(ch, id) for ch in str1 for id in range(2)]
print ('comprehension with 2 for loops: ', lst)

# pair creation with zip
str1 = 'ab'
lst1 = ['1', '2']
lst = [(ch, id) for ch, id in zip(str1, lst1)]
print ('pair creation with zip in comprehension: ', lst)

list of numbers : [0, 1, 2, 3, 4, 5]
list of squares:  [0, 1, 4, 9, 16, 25]
list of even numbers:  [0, 2, 4]
comprehension with 2 for loops:  [('a', 0), ('a', 1), ('b', 0), ('b', 1)]
pair creation with zip in comprehension:  [('a', '1'), ('b', '2')]


# for
- <font color=blue> for works on any iterable like strings, lists, tuples, dictionaries </font>

## for example on lists

In [32]:
fruits = ["apples", "oranges", "mangoes"]
for fruit in fruits:
    print (fruit)

apples
oranges
mangoes


## for example on strings

In [1]:
fruit = 'apple'
for ch in fruit:
    print (ch)

a
p
p
l
e


## for using range function
- range generates the sequence of numbers
- **syntax of range: range(start,stop,step)**
- start is optional, if start is not specified starts from 0. step is optional, default step is 1

In [34]:
# example
for i in range(0,5):
 print ("iteration cnt:", i)

# step count 2
for i in range(0,5,2):
    print ('step 2: iteration cnt:', i)

iteration cnt: 0
iteration cnt: 1
iteration cnt: 2
iteration cnt: 3
iteration cnt: 4
step 2: iteration cnt: 0
step 2: iteration cnt: 2
step 2: iteration cnt: 4


## main function
- python does not require a main function to be created, it is better to create for clarity
- every python file can have a function/main call, but when this file imported as module these function calls also gets executed
- to avoid unnecessary execution of function calls in imported module, we can create conditional function calls with __name__

In [14]:
# __name__ example
def fn_name_example():
 print ('welcome to function __name__ example')

if __name__ == "__main__":
 fn_name_example()
 print ('name is set to __main__ when this file is directly executed, it is not when executed from imported file')

welcome to function __name__ example
name is set to __main__ when this file is directly executed, it is not when executed from imported file


## global keyword
- global keyword should be used to assign value to a global variable inside a function

In [15]:
# example
val = 25
def fn_global():
 # global keyword to reference global variable, gives compilation error without
 global val
 print ('inside fn: val is', val)
 val = 50
 print ('inside fn: val is', val)

fn_global()
print ('outside fn: val is', val)

inside fn: val is 25
inside fn: val is 50
outside fn: val is 50


## function call by reference vs value

## keyword argument

## default arguments

## variable number of arguments

## anonymous functions

## '''doc strings''' : documentatin strings

In [16]:
def find_max_doc(x, y):
 # docstring of the function
 '''fn description: finds max value of 2 numbers '''
 if x > y:
  print ('max value is',x)
 else:
  print ('max value is',y)

print (find_max_doc.__doc__)
find_max_doc(2,3)

fn description: finds max value of 2 numbers 
max value is 3


# modules
- A module allows you to logically organize your Python code, to reuse a number of functions in other programs 
- Simply, a module is a file consisting of Python code
- A module can define functions, classes and variables. A module can also include runnable code

In [17]:
# example
import sys

print ('command line args')
for i in sys.argv:
 #prints cmd arg strings, not numbers
 print (i)

command line args
C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py
-f
C:\Users\Admin\AppData\Roaming\jupyter\runtime\kernel-06e48333-dc11-4a4d-8c08-1be42de18b20.json


# packages
- A package is a hierarchical file directory structure that defines a single Python application environment that consists of modules and subpackages
- **Packages are just folders of modules with a special init.py file** that indicates to Python that this folder is special because it contains Python modules

In [18]:
# example
print ('''- To make all of your functions available when you've imported a directory (ex_dir) as a package, 
you need to put explicit import statements in __init__.py as follows,
Then we can directly import the package/directory name (ex_dir) instead of individual modules
import ex_dir ''')

- To make all of your functions available when you've imported a directory (ex_dir) as a package, 
you need to put explicit import statements in __init__.py as follows,
Then we can directly import the package/directory name (ex_dir) instead of individual modules
import ex_dir 


# Object oriented programming (oop)
- **Class attributes (fields and methods):**
    - Variables that belong to an object or class are referred to as fields. Objects can also have functionality by using functions that belong to a class. Such functions are called methods of the class. 
    - Collectively, the fields and methods can be referred to as the attributes of that class
- Fields are of two types,
    - they can belong to each instance/object of the class or they can belong to the class itself. They are called **instance variables and class variables** respectively
    
- self:
    - Class methods have only one specific difference from ordinary functions, they must have an extra first name that has to be added to the beginning of the parameter list, but you do not give a value for this parameter when you call the method, Python will provide it. 
    - This particular variable refers to the object itself, and by convention, it is given the name self .
    - We can use any name other than self, but better to use self.
    - The self in Python is equivalent to the this pointer in C++

## simple class and object creation example

In [19]:
class Person:
  def say_hi(self):
    print ('Hello, welcome to class and oop')

# object creation using class name
obj = Person()
# calling class method using object
obj.say_hi()

Hello, welcome to class and oop


## object variable creation and name space

In [20]:
class Person:
  def say_hi(self):
    self.cnt = 1
    print ('Hello, welcome to class and oop')

# object creation using class name
obj1 = Person()
obj2 = Person()

print('obj1 name space\n', obj1.__dict__)

# create object variables (better to do it inside class)
obj2.var = 2
print('obj2 name space\n', obj2.__dict__)

obj1 name space
 {}
obj2 name space
 {'var': 2}


## __init__ method: Class constructor
- The __init__ method is run as soon as an object of a class is instantiated, the method is useful to do any initialization you want to do with your object
- Notice the double underscores (dunder) both at the beginning and at the end of the name

In [21]:
# example

class Person:
  # default constructor
  def __init__(self, name):
    # Note: self.name means that there is a field called "name" that is part of the object called "self" 
    self.name = name

  def say_hi(self):
    print ('Hello, my name is', self.name)

# object creation calls init constructor
p = Person('Swaroop')
p.say_hi()

Hello, my name is Swaroop


## example for class/instance fields and class/static/instance methods

In [4]:
class Test_Class:

 # class variable/field (can be accessed using class or object)
 obj_cnt = 0

 # default constructor
 def __init__(self, name):
  # accessing class variable
  Test_Class.obj_cnt += 1
  # obect variables will be directly created when required ?
  # object field (can be accessed using only objects)
  self.name = name
  self.val = 0
  print ('Welcome to Test_Class: Object name ', self)
  print ('obj_cnt value: ', Test_Class.obj_cnt, '\n')
  

 # object method (can be called using an object)
 def obj_fn(self, val):
  self.val += 1
  # obect variables will be directly created when required ?
  self.sum = self.val + val
  print ('Welcome to obj_fn: Object name ', self)
  print ('obj_fn counter (object value): ', self.val)
  print ('self.name: ', self.name, ', self.sum: ', self.sum, '\n')


 # class method using a below token @classmethod (can be called using Class, can also be called using object)
 @classmethod
 def cls_fn(cls):
  print ('Welcome to cls_fn (class function) created with @classmethod')
  print ('objects cnt: ', Test_Class.obj_cnt)
  # can not access any object variables
  # print 'val: ', cls.val
  print ('!! classmethod can not access any object variables', '\n')


 # static method using a below token @staticmethod (like a normal function does not take object, class as 1st arguments)
 @staticmethod
 def static_fn():
  print ('Welcome to static_fn (static function) created with @staticmethod \n')
  #print 'objects cnt: ', Test_Class.obj_cnt


# create an object
obj_1 = Test_Class('sirish')
# call object function
obj_1.obj_fn(24)
# call class function with object
obj_1.cls_fn()
# call class function using class name
Test_Class.cls_fn()
# call static function using object
obj_1.static_fn()
# call static function using class
Test_Class.static_fn()


# second object
obj_2 = Test_Class('kumar')
obj_2.obj_fn(99)
obj_2.cls_fn()
Test_Class.cls_fn()
Test_Class.static_fn()

Welcome to Test_Class: Object name  <__main__.Test_Class object at 0x0000019747AE6438>
obj_cnt value:  1 

Welcome to obj_fn: Object name  <__main__.Test_Class object at 0x0000019747AE6438>
obj_fn counter (object value):  1
self.name:  sirish , self.sum:  25 

Welcome to cls_fn (class function) created with @classmethod
objects cnt:  1
!! classmethod can not access any object variables 

Welcome to cls_fn (class function) created with @classmethod
objects cnt:  1
!! classmethod can not access any object variables 

Welcome to static_fn (static function) created with @staticmethod 

Welcome to static_fn (static function) created with @staticmethod 

Welcome to Test_Class: Object name  <__main__.Test_Class object at 0x0000019747AE65C0>
obj_cnt value:  2 

Welcome to obj_fn: Object name  <__main__.Test_Class object at 0x0000019747AE65C0>
obj_fn counter (object value):  1
self.name:  kumar , self.sum:  100 

Welcome to cls_fn (class function) created with @classmethod
objects cnt:  2
!! cl

# File I/O

## file object attributes
- Once a file is opened and you have one file object, you can get various information related to that file.

- Here is a list of all attributes related to file object:
    - Attribute:        Description:
    - file.closed       Returns true if file is closed, false otherwise.
    - file.mode         Returns access mode with which file was opened.
    - file.name         Returns name of the file.
    - file.softspace    Returns false if space explicitly required with print, true otherwise. 

## example for file open, close and attributes

In [23]:
fp = open("foo.txt", "wb")
print ("Name of the file: ", fp.name)
print ("Opening mode : ", fp.mode)
print ("Closed or not : ", fp.closed)
fp.close()
print ("Closed or not : ", fp.closed)

Name of the file:  foo.txt
Opening mode :  wb
Closed or not :  False
Closed or not :  True


## read and write files
- use read() and write() methods to read and write files

In [24]:
# example

fp = open("foo.txt", "w")
fp.write( "Python is a great language.\n Yeah its great!!\n");
fp.close()

fp = open("foo.txt", "r")
str = fp.read()
print (str)
fp.close()

Python is a great language.
 Yeah its great!!



## file positions
- The tell() method tells you the current position within the file
- The seek(offset[, from]) method changes the current file position

# OS module
- The OS module in python provides functions for interacting with the operating system

## os.getcwd(): get current working directory

In [25]:
import os
print(os.getcwd())

D:\learning-git\python\learn


## os.listdir(): list directories and files

In [26]:
import os
print(os.listdir())

['.ipynb_checkpoints', '.python_learn.py.swn', '.python_learn.py.swo', '.python_learn.py.swp', '.python_learn.py.un~', 'byte_of_python.pdf', 'foo.txt', 'python_learn.py', 'python_learn.py~', 'python_learn_note.ipynb', 'python_syllabus.txt', 'python_tips.py', 'temp1.txt', 'test.py', 'test_module.py']


## os.makedirs(): create directories using path
- **creates a path, creates the directories if any directory is not available in the path**

## os.rename() : rename files/directories

In [27]:
import os
with open('temp.txt', 'w') as f:
    pass
# list directories and files after temp file creation
print(os.listdir())

# rename file
os.remove('temp1.txt')
os.rename('temp.txt', 'temp1.txt')
# list directories and files after renaming
print('\n list and directories after renaming')
print(os.listdir())

['.ipynb_checkpoints', '.python_learn.py.swn', '.python_learn.py.swo', '.python_learn.py.swp', '.python_learn.py.un~', 'byte_of_python.pdf', 'foo.txt', 'python_learn.py', 'python_learn.py~', 'python_learn_note.ipynb', 'python_syllabus.txt', 'python_tips.py', 'temp.txt', 'temp1.txt', 'test.py', 'test_module.py']

 list and directories after renaming
['.ipynb_checkpoints', '.python_learn.py.swn', '.python_learn.py.swo', '.python_learn.py.swp', '.python_learn.py.un~', 'byte_of_python.pdf', 'foo.txt', 'python_learn.py', 'python_learn.py~', 'python_learn_note.ipynb', 'python_syllabus.txt', 'python_tips.py', 'temp1.txt', 'test.py', 'test_module.py']


# try: for error handling
- try block is used to handle the exception gracefully
- default exception is called for any exception, however we can have custom exceptions for clarity
- else block will be executed when no exception raised
- finally block is called irrespective of exceptions, can be used to de-init/close other stuff

In [28]:
# default error exception
try:
    f = open('test.yuv', 'r')
except Exception:
    print("default: File opening error")

# specific error exception
try:
    f = open('test.yuv', 'r')
except FileNotFoundError:
    print("File opening error")
except Exception:
    pass

# else part if no error
try:
    pass
except Exception:
    pass
else:
    print('else part when no exception')
    
# else part if no error
try:
    pass
except Exception:
    pass
else:
    print('else part when no exception')
finally:
    print('execute finally block irrespective of exception status')
    
# raise exception
try:
    val = -1
    # here no issue, but we can raise custom exceptions based on need
    if(val == -1):
        raise Exception
except Exception:
    print("raised error")

default: File opening error
File opening error
else part when no exception
else part when no exception
execute finally block irrespective of exception status
raised error


# Python Regular Expression

## raw string
- raw string prefixed with character 'r', which indicates python to interpret literally the string as it is, not to treat the special characters in any special way

In [7]:
# raw string example
string = '...\t :normal string after tab'
raw_string = r'''...\t :raw string interpreted literally as it is 
without any special meaning to any special characters'''

print(string)
print(raw_string)

...	 :normal string after tab
...\t :raw string interpreted literally as it is 
without any special meaning to any special characters


## find match: finditer

In [26]:
# example
import re
search_string = '''hi, hello to search hi with big HI python.com number 1 and java 2'''

# compile the pattern raw string
pattern = re.compile(r'hi')
# find match in string
matches = pattern.finditer(search_string)
# print all matches with indexes
print(pattern)
for match in matches:
    print(match)
    
# match all chars
pattern = re.compile(r'\d')
# match digits in string with \d
matches = pattern.finditer(search_string)
# print all matches
print('\n', pattern, '\d to match digits')
for match in matches:
    print(match)    

re.compile('hi')
<_sre.SRE_Match object; span=(0, 2), match='hi'>
<_sre.SRE_Match object; span=(20, 22), match='hi'>

 re.compile('\\d') \d to match digits
<_sre.SRE_Match object; span=(53, 54), match='1'>
<_sre.SRE_Match object; span=(64, 65), match='2'>


# Python Exercise Examples: Basics
https://www.w3resource.com/python-exercises/

## Print current date time

In [29]:
import datetime
now = datetime.datetime.now()
print ("Current date and time : ")
print (now.strftime("%Y-%m-%d %H:%M:%S"))

Current date and time : 
2018-11-24 20:30:47


## Check a file present or not

In [30]:
import os
import os.path
open('abc.txt', 'w')
print(os.path)
print(os.path.isfile('abc.txt'))
os.remove('abc.txt')
print(os.path.isfile('abc.txt'))

<module 'ntpath' from 'C:\\Users\\Admin\\Anaconda3\\lib\\ntpath.py'>
True
False


## Print number of CPU's running

In [31]:
import multiprocessing
print(multiprocessing.cpu_count())

4


## Compare all values in a list with a number
- all:
    - The all() method returns True when all elements in the given ** iterable ** are true. If not, it returns False.

In [53]:
num = [5,8,9]
print(all(x > 4 for x in num))
print(all(x > 7 for x in num))

True
False


## Profile execution time of a program

In [54]:
from timeit import default_timer
def timer(n):
    start = default_timer()
    # some code here
    sum = 0
    for row in range(0,n):
        sum *= row
    print(default_timer() - start)

timer(10)
timer(100)

7.153053559250111e-06
1.6172121149793384e-05


# NumPy

## NumPy basics

### create 1D numpy array with value 10

In [76]:
# example
import numpy as np
array0 = np.zeros(5)
array1 = np.ones(5)
array2 = np.ones(5)*10
array3 = np.array([10, 10, 10, 10, 10])

print(array0)
print(array1)
print(array2)
print(array3)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[10. 10. 10. 10. 10.]
[10 10 10 10 10]


### create constant array with full

In [77]:
import numpy as np
array1 = np.full((2,3,4), 6)
print('array shape: {}, number of dimensions: {}'.format(array1.shape, array1.ndim))
print(array1)

array shape: (2, 3, 4), number of dimensions: 3
[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


### create 1D numpy array with values range from 10 to 20
- ** use arrange method**

In [28]:
# example
import numpy as np
array1 = np.arange(10, 21)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20]


### create 1D numpy array with random values below 10

In [42]:
# example
import numpy as np
array1 = np.random.randint(0, 11, 5)
print(array1)

[0 0 4 4 3]


### create 2D numpy array and iterate

In [37]:
# example
import numpy as np
array1 = np.arange(10, 22).reshape(3,4)

# original array
print('original array\n', array1)

# iterate over each element sequentially
print('\nprint each value sequentially')
for val in np.nditer(array1):
    print(val, end="  ")

original array
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

print each value sequentially
10  11  12  13  14  15  16  17  18  19  20  21  

### create nD array

In [70]:
# example
import numpy as np

array1 = np.array([[0,1, 2, 3],[4,5, 6, 7], [8, 9,10, 11]])
print('array shape', array1.shape)
print(array1, '\n')

print('array creation with explicity initiation')
array1 = np.array([[[0,1, 2, 3],[4,5, 6, 7], [8, 9,10, 11]], [[12,13, 14, 15],[16,17, 18, 19], [20, 21,22,23]]])
print('array shape', array1.shape)
print(array1, '\n')

print('array creation with auto fill')
array1 = np.arange(0,24).reshape(2,3,4)
print('array shape', array1.shape)
print(array1, '\n')

array shape (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

array creation with explicity initiation
array shape (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

array creation with auto fill
array shape (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 



# Pandas

# PILLOW