<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy" data-toc-modified-id="NumPy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy</a></span><ul class="toc-item"><li><span><a href="#NumPy-basics" data-toc-modified-id="NumPy-basics-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>NumPy basics</a></span><ul class="toc-item"><li><span><a href="#create-1D-numpy-array-with-value-10" data-toc-modified-id="create-1D-numpy-array-with-value-10-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>create 1D numpy array with value 10</a></span></li><li><span><a href="#create-constant-array-with-full" data-toc-modified-id="create-constant-array-with-full-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>create constant array with full</a></span></li><li><span><a href="#create-1D-numpy-array-with-values-range-from-10-to-20" data-toc-modified-id="create-1D-numpy-array-with-values-range-from-10-to-20-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>create 1D numpy array with values range from 10 to 20</a></span></li><li><span><a href="#create-1D-numpy-array-with-random-values-below-10" data-toc-modified-id="create-1D-numpy-array-with-random-values-below-10-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>create 1D numpy array with random values below 10</a></span></li><li><span><a href="#create-2D-numpy-array-and-iterate" data-toc-modified-id="create-2D-numpy-array-and-iterate-1.1.5"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>create 2D numpy array and iterate</a></span></li><li><span><a href="#create-nD-array" data-toc-modified-id="create-nD-array-1.1.6"><span class="toc-item-num">1.1.6&nbsp;&nbsp;</span>create nD array</a></span></li></ul></li></ul></li></ul></div>

# NumPy

## NumPy basics

### create 1D numpy array with value 10

In [76]:
# example
import numpy as np
array0 = np.zeros(5)
array1 = np.ones(5)
array2 = np.ones(5)*10
array3 = np.array([10, 10, 10, 10, 10])

print(array0)
print(array1)
print(array2)
print(array3)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[10. 10. 10. 10. 10.]
[10 10 10 10 10]


### create constant array with full

In [77]:
import numpy as np
array1 = np.full((2,3,4), 6)
print('array shape: {}, number of dimensions: {}'.format(array1.shape, array1.ndim))
print(array1)

array shape: (2, 3, 4), number of dimensions: 3
[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


### create 1D numpy array with values range from 10 to 20
- ** use arrange method**

In [28]:
# example
import numpy as np
array1 = np.arange(10, 21)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20]


### create 1D numpy array with random values below 10

In [42]:
# example
import numpy as np
array1 = np.random.randint(0, 11, 5)
print(array1)

[0 0 4 4 3]


### create 2D numpy array and iterate

In [37]:
# example
import numpy as np
array1 = np.arange(10, 22).reshape(3,4)

# original array
print('original array\n', array1)

# iterate over each element sequentially
print('\nprint each value sequentially')
for val in np.nditer(array1):
    print(val, end="  ")

original array
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

print each value sequentially
10  11  12  13  14  15  16  17  18  19  20  21  

### create nD array

In [70]:
# example
import numpy as np

array1 = np.array([[0,1, 2, 3],[4,5, 6, 7], [8, 9,10, 11]])
print('array shape', array1.shape)
print(array1, '\n')

print('array creation with explicity initiation')
array1 = np.array([[[0,1, 2, 3],[4,5, 6, 7], [8, 9,10, 11]], [[12,13, 14, 15],[16,17, 18, 19], [20, 21,22,23]]])
print('array shape', array1.shape)
print(array1, '\n')

print('array creation with auto fill')
array1 = np.arange(0,24).reshape(2,3,4)
print('array shape', array1.shape)
print(array1, '\n')

array shape (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

array creation with explicity initiation
array shape (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

array creation with auto fill
array shape (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

